version: "3"
name: weight-tracker
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_URL: https://github.com/bartb142/weight-tracking.git
        PORT: 80
    container_name: weight-tracker
    hostname: weight-tracker
    command: ["streamlit", "run", "Home.py", "--server.port=80", "--server.address=0.0.0.0"]
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/app
